// Generated by scripts/import-ai-companies.ts. Do not edit manually.
export type OtherCareerProvider =
  | 'workable'
  | 'recruitee'
  | 'smartrecruiters'
  | 'teamtailor'
  | 'bamboohr'
  | 'workday';
export interface OtherAiCompanyBoard {
  readonly company: string;
  readonly provider: OtherCareerProvider;
  readonly slug: string;
  readonly url: string;
}

export const AI_COMPANY_OTHER_BOARDS = [
  {
    company: '10Web',
    provider: 'bamboohr',
    slug: '10web',
    url: 'https://10web.bamboohr.com/careers',
  },
  {
    company: 'Graphwise',
    provider: 'bamboohr',
    slug: 'graphwise',
    url: 'https://graphwise.bamboohr.com/careers/97?source=aWQ9MjY%3D',
  },
  {
    company: 'Replenit',
    provider: 'bamboohr',
    slug: 'replenit',
    url: 'https://replenit.bamboohr.com/careers/33',
  },
  {
    company: 'Freeday',
    provider: 'recruitee',
    slug: 'freeday',
    url: 'https://freeday.recruitee.com/',
  },
  {
    company: 'Greyparrot Ai',
    provider: 'recruitee',
    slug: 'greyparrotai',
    url: 'https://greyparrotai.recruitee.com/o/open-application',
  },
  {
    company: 'Hyperion Robotics',
    provider: 'teamtailor',
    slug: 'hyperionrobotics',
    url: 'https://hyperionrobotics.teamtailor.com/',
  },
  {
    company: 'AI Acquisition',
    provider: 'workable',
    slug: 'ai-acquisition',
    url: 'https://apply.workable.com/ai-acquisition/?lng=en',
  },
  {
    company: 'AION: The Everyday AI Platform',
    provider: 'workable',
    slug: 'aion',
    url: 'https://apply.workable.com/aion',
  },
  {
    company: 'Kleva Tech, Inc.',
    provider: 'workable',
    slug: 'kleva-tech',
    url: 'https://apply.workable.com/kleva-tech/',
  },
  {
    company: 'Soul Machines',
    provider: 'workable',
    slug: 'soul-machines-ltd',
    url: 'https://apply.workable.com/soul-machines-ltd/?lng=en',
  },
  {
    company: 'Cerence Inc.',
    provider: 'workday',
    slug: 'cerence.wd5.myworkdayjobs.com',
    url: 'https://cerence.wd5.myworkdayjobs.com/Cerence',
  },
] as const satisfies readonly OtherAiCompanyBoard[];
