export interface WatchlistCompany {
  readonly name: string;
  readonly ats: 'greenhouse' | 'lever' | 'ashby';
  readonly slug: string;
  readonly tier: 1 | 2 | 3;
  readonly domain: string;
}

export const COMPANIES: readonly WatchlistCompany[] = [
  // ── Lever ────────────────────────────────────────────────────────────────────
  { name: 'LI.FI', ats: 'lever', slug: 'li.fi', tier: 1, domain: 'web3-bridge' },
  { name: 'Wormhole Labs', ats: 'lever', slug: 'wormhole-labs', tier: 1, domain: 'web3-bridge' },
  { name: 'Risk Labs (UMA Protocol)', ats: 'lever', slug: 'risk-labs', tier: 1, domain: 'web3-oracle' },
  { name: 'Across Protocol', ats: 'lever', slug: 'across-protocol', tier: 1, domain: 'web3-bridge' },
  { name: 'Hyperlane', ats: 'lever', slug: 'hyperlane', tier: 1, domain: 'web3-bridge' },
  { name: 'Biconomy', ats: 'lever', slug: 'biconomy', tier: 1, domain: 'web3-infra' },
  { name: 'Gelato Network', ats: 'lever', slug: 'gelato-network', tier: 1, domain: 'web3-infra' },
  { name: 'Flashbots', ats: 'lever', slug: 'flashbots', tier: 1, domain: 'web3-mev' },
  { name: 'QuickNode', ats: 'lever', slug: 'quicknode', tier: 1, domain: 'web3-infra' },
  { name: 'Maple Finance', ats: 'lever', slug: 'maple-finance', tier: 2, domain: 'web3-defi' },
  { name: 'Kraken', ats: 'lever', slug: 'kraken', tier: 2, domain: 'web3-exchange' },
  { name: 'Celestia', ats: 'lever', slug: 'celestia', tier: 1, domain: 'web3-l1-infra' },
  { name: 'Reservoir', ats: 'lever', slug: 'reservoir', tier: 1, domain: 'web3-nft' },
  { name: 'Magic Eden', ats: 'lever', slug: 'magic-eden', tier: 2, domain: 'web3-nft' },
  { name: 'Jito Labs', ats: 'lever', slug: 'jito-labs', tier: 1, domain: 'web3-mev' },
  { name: 'Trail of Bits', ats: 'lever', slug: 'trail-of-bits', tier: 1, domain: 'security' },
  { name: 'Halborn Security', ats: 'lever', slug: 'halborn', tier: 1, domain: 'security' },
  { name: 'Immunefi', ats: 'lever', slug: 'immunefi', tier: 2, domain: 'security' },
  { name: 'AssemblyAI', ats: 'lever', slug: 'assemblyai', tier: 1, domain: 'ai-infra' },
  { name: 'Groq', ats: 'lever', slug: 'groq', tier: 2, domain: 'ai-infra' },
  { name: 'Replicate', ats: 'lever', slug: 'replicate', tier: 1, domain: 'ai-infra' },
  { name: 'Inngest', ats: 'lever', slug: 'inngest', tier: 1, domain: 'backend-saas' },
  { name: 'Fly.io', ats: 'lever', slug: 'fly', tier: 1, domain: 'backend-saas' },
  { name: 'WorkOS', ats: 'lever', slug: 'workos', tier: 1, domain: 'backend-saas' },
  { name: 'Dagger.io', ats: 'lever', slug: 'dagger', tier: 1, domain: 'backend-saas' },
  { name: 'Lago', ats: 'lever', slug: 'lago', tier: 2, domain: 'backend-saas' },
  { name: 'Orb', ats: 'lever', slug: 'orb', tier: 2, domain: 'backend-saas' },
  { name: 'Render', ats: 'lever', slug: 'render', tier: 2, domain: 'backend-saas' },
  { name: 'Vellum AI', ats: 'lever', slug: 'vellum-ai', tier: 2, domain: 'ai-infra' },
  // ── Greenhouse ────────────────────────────────────────────────────────────────
  { name: 'Uniswap Labs', ats: 'greenhouse', slug: 'uniswaplabs', tier: 1, domain: 'web3-defi' },
  { name: 'OP Labs (Optimism)', ats: 'greenhouse', slug: 'oplabs', tier: 1, domain: 'web3-l2' },
  { name: 'Arbitrum Foundation', ats: 'greenhouse', slug: 'arbitrumfoundation', tier: 1, domain: 'web3-l2' },
  { name: 'LayerZero Labs', ats: 'greenhouse', slug: 'layerzero', tier: 1, domain: 'web3-bridge' },
  { name: 'Axelar Network', ats: 'greenhouse', slug: 'axelar', tier: 1, domain: 'web3-bridge' },
  { name: 'Chainlink Labs', ats: 'greenhouse', slug: 'chainlink', tier: 1, domain: 'web3-oracle' },
  { name: 'The Graph Protocol', ats: 'greenhouse', slug: 'thegraphfoundation', tier: 1, domain: 'web3-infra' },
  { name: 'Alchemy', ats: 'greenhouse', slug: 'alchemy-2', tier: 1, domain: 'web3-infra' },
  { name: 'WalletConnect', ats: 'greenhouse', slug: 'walletconnect', tier: 1, domain: 'web3-auth' },
  { name: 'Safe (Gnosis Safe)', ats: 'greenhouse', slug: 'safe-global', tier: 1, domain: 'web3-wallet' },
  { name: 'Gnosis', ats: 'greenhouse', slug: 'gnosis', tier: 1, domain: 'web3-infra' },
  { name: 'Aave', ats: 'greenhouse', slug: 'aave-companies', tier: 1, domain: 'web3-defi' },
  { name: 'Lido Finance', ats: 'greenhouse', slug: 'lidofinance', tier: 1, domain: 'web3-defi' },
  { name: 'Ondo Finance', ats: 'greenhouse', slug: 'ondofinance', tier: 1, domain: 'web3-defi' },
  { name: 'dYdX', ats: 'greenhouse', slug: 'dydx', tier: 1, domain: 'web3-defi' },
  { name: 'Circle', ats: 'greenhouse', slug: 'circle', tier: 1, domain: 'web3-fintech' },
  { name: 'Paxos', ats: 'greenhouse', slug: 'paxos', tier: 1, domain: 'web3-fintech' },
  { name: 'Anchorage Digital', ats: 'greenhouse', slug: 'anchoragebitcoin', tier: 1, domain: 'web3-fintech' },
  { name: 'Fireblocks', ats: 'greenhouse', slug: 'fireblocks', tier: 1, domain: 'web3-fintech' },
  { name: 'Copper', ats: 'greenhouse', slug: 'copper', tier: 2, domain: 'web3-fintech' },
  { name: 'BitGo', ats: 'greenhouse', slug: 'bitgo', tier: 2, domain: 'web3-fintech' },
  { name: 'Coinbase', ats: 'greenhouse', slug: 'coinbase', tier: 2, domain: 'web3-exchange' },
  { name: 'Gemini', ats: 'greenhouse', slug: 'gemini', tier: 2, domain: 'web3-exchange' },
  { name: 'zkSync / Matter Labs', ats: 'greenhouse', slug: 'matterlabs', tier: 1, domain: 'web3-l2' },
  { name: 'Polygon Labs', ats: 'greenhouse', slug: 'polygon', tier: 1, domain: 'web3-l2' },
  { name: 'Starkware / StarkNet', ats: 'greenhouse', slug: 'starkware', tier: 2, domain: 'web3-l2' },
  { name: 'EigenLayer / Eigen Labs', ats: 'greenhouse', slug: 'eigenlabs', tier: 2, domain: 'web3-l1-infra' },
  { name: 'Immutable X', ats: 'greenhouse', slug: 'immutable', tier: 2, domain: 'web3-gaming' },
  { name: 'OpenSea', ats: 'greenhouse', slug: 'opensea', tier: 2, domain: 'web3-nft' },
  { name: 'OpenZeppelin', ats: 'greenhouse', slug: 'openzeppelin', tier: 1, domain: 'security' },
  { name: 'Perplexity', ats: 'greenhouse', slug: 'perplexity', tier: 1, domain: 'ai-infra' },
  { name: 'ElevenLabs', ats: 'greenhouse', slug: 'elevenlabs', tier: 1, domain: 'ai-infra' },
  { name: 'Deepgram', ats: 'greenhouse', slug: 'deepgram', tier: 1, domain: 'ai-infra' },
  { name: 'Cohere', ats: 'greenhouse', slug: 'cohere', tier: 2, domain: 'ai-infra' },
  { name: 'Together AI', ats: 'greenhouse', slug: 'togetherai', tier: 2, domain: 'ai-infra' },
  { name: 'Fireworks AI', ats: 'greenhouse', slug: 'fireworks-ai', tier: 2, domain: 'ai-infra' },
  { name: 'Weights & Biases', ats: 'greenhouse', slug: 'wandb', tier: 2, domain: 'ai-infra' },
  { name: 'Hugging Face', ats: 'greenhouse', slug: 'huggingface', tier: 2, domain: 'ai-infra' },
  { name: 'Vercel', ats: 'greenhouse', slug: 'vercel', tier: 1, domain: 'backend-saas' },
  { name: 'PlanetScale', ats: 'greenhouse', slug: 'planetscale', tier: 2, domain: 'backend-saas' },
  { name: 'CockroachLabs', ats: 'greenhouse', slug: 'cockroachlabs', tier: 2, domain: 'backend-saas' },
  { name: 'Redpanda Data', ats: 'greenhouse', slug: 'redpandadata', tier: 1, domain: 'backend-saas' },
  { name: 'Temporal Technologies', ats: 'greenhouse', slug: 'temporaltechnologies', tier: 1, domain: 'backend-saas' },
  { name: 'Novu', ats: 'greenhouse', slug: 'novu', tier: 1, domain: 'backend-saas' },
  { name: 'PostHog', ats: 'greenhouse', slug: 'posthog', tier: 1, domain: 'backend-saas' },
  { name: 'Sentry', ats: 'greenhouse', slug: 'sentry', tier: 2, domain: 'backend-saas' },
  { name: 'Grafana Labs', ats: 'greenhouse', slug: 'grafana', tier: 2, domain: 'backend-saas' },
  { name: 'Cloudflare', ats: 'greenhouse', slug: 'cloudflare', tier: 2, domain: 'backend-saas' },
  { name: 'Stytch', ats: 'greenhouse', slug: 'stytch', tier: 1, domain: 'backend-saas' },
  { name: 'Permit.io', ats: 'greenhouse', slug: 'permitio', tier: 1, domain: 'backend-saas' },
  { name: 'Kong', ats: 'greenhouse', slug: 'kong', tier: 2, domain: 'backend-saas' },
  { name: 'Merge API', ats: 'greenhouse', slug: 'mergeapi', tier: 2, domain: 'backend-saas' },
  { name: 'Airbyte', ats: 'greenhouse', slug: 'airbyte', tier: 2, domain: 'backend-saas' },
  { name: 'dbt Labs', ats: 'greenhouse', slug: 'dbtlabs', tier: 2, domain: 'backend-saas' },
  { name: 'Materialize', ats: 'greenhouse', slug: 'materialize', tier: 2, domain: 'backend-saas' },
  { name: 'Retool', ats: 'greenhouse', slug: 'retool', tier: 2, domain: 'backend-saas' },
  { name: 'Stripe', ats: 'greenhouse', slug: 'stripe', tier: 3, domain: 'fintech' },
  { name: 'Plaid', ats: 'greenhouse', slug: 'plaid', tier: 2, domain: 'fintech' },
  { name: 'Brex', ats: 'greenhouse', slug: 'brex', tier: 2, domain: 'fintech' },
  { name: 'Datadog', ats: 'greenhouse', slug: 'datadog', tier: 3, domain: 'backend-saas' },
  { name: 'Unstoppable Domains', ats: 'greenhouse', slug: 'unstoppabledomains', tier: 2, domain: 'web3-infra' },
  { name: 'Anyscale', ats: 'greenhouse', slug: 'anyscale', tier: 2, domain: 'ai-infra' },
  { name: 'Pinecone', ats: 'greenhouse', slug: 'pinecone', tier: 2, domain: 'ai-infra' },
  { name: 'Weaviate', ats: 'greenhouse', slug: 'weaviate', tier: 2, domain: 'ai-infra' },
  // ── Ashby ─────────────────────────────────────────────────────────────────────
  { name: 'Goldsky', ats: 'ashby', slug: 'goldsky', tier: 1, domain: 'web3-infra' },
  { name: 'Helius (Solana RPC)', ats: 'ashby', slug: 'helius', tier: 1, domain: 'web3-infra' },
  { name: 'Privy', ats: 'ashby', slug: 'privy', tier: 1, domain: 'web3-auth' },
  { name: 'Dynamic', ats: 'ashby', slug: 'dynamic', tier: 1, domain: 'web3-auth' },
  { name: 'Ethena Labs', ats: 'ashby', slug: 'ethena-labs', tier: 1, domain: 'web3-defi' },
  { name: 'Zora', ats: 'ashby', slug: 'zora', tier: 2, domain: 'web3-nft' },
  { name: 'Exa AI', ats: 'ashby', slug: 'exa', tier: 1, domain: 'ai-infra' },
  { name: 'Braintrust', ats: 'ashby', slug: 'braintrustdata', tier: 1, domain: 'ai-infra' },
  { name: 'LangChain', ats: 'ashby', slug: 'langchain', tier: 2, domain: 'ai-infra' },
  { name: 'Modal', ats: 'ashby', slug: 'modal-labs', tier: 1, domain: 'ai-infra' },
  { name: 'Supabase', ats: 'ashby', slug: 'supabase', tier: 1, domain: 'backend-saas' },
  { name: 'Neon Database', ats: 'ashby', slug: 'neon', tier: 1, domain: 'backend-saas' },
  { name: 'Axiom', ats: 'ashby', slug: 'axiom', tier: 1, domain: 'backend-saas' },
  { name: 'Railway', ats: 'ashby', slug: 'railway', tier: 2, domain: 'backend-saas' },
  { name: 'Linear', ats: 'ashby', slug: 'linear', tier: 2, domain: 'backend-saas' },
  { name: 'Depot', ats: 'ashby', slug: 'depot', tier: 2, domain: 'backend-saas' },
  { name: 'Speakeasy', ats: 'ashby', slug: 'speakeasy', tier: 2, domain: 'backend-saas' },
  { name: 'Fern', ats: 'ashby', slug: 'fern', tier: 2, domain: 'backend-saas' },
  { name: 'Zuplo', ats: 'ashby', slug: 'zuplo', tier: 1, domain: 'backend-saas' },
  { name: 'LlamaIndex', ats: 'ashby', slug: 'llamaindex', tier: 2, domain: 'ai-infra' },
  { name: 'Turnkey', ats: 'ashby', slug: 'turnkey', tier: 1, domain: 'web3-auth' },
  { name: 'Cartesia', ats: 'ashby', slug: 'cartesia', tier: 2, domain: 'ai-infra' },
] as const;
